name: update-coverage-badge
on:
  push:
    branches: [main]

jobs:
  update-coverage-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.13"

      - name: Install deps
        run: uv sync --all-extras --locked

      - name: Generate badge
        run: uv run poe "ci:update_coverage_badge"

      - name: Commit coverage badge
        if: github.event_name == 'push' && env.ACT != 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update coverage badge"
          file_pattern: "coverage.svg"
          branch: ${{ github.ref_name }}
