name: Test Template on PR

on:
  pull_request:
    branches:
      - template

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          path: template
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          working-directory: ${{ github.workspace }}/template
          version: "latest"
          python-version: "3.13"

        # comment
      - name: Render template
        run: |
          mkdir ${{ github.workspace }}/rendered-project
          cd ${{ github.workspace }}/template
          uvx copier copy \
            --overwrite \
            --defaults \
            -d description="Add your description here" \
            -d include_dockerfile=true \
            -d module_name=postmodern \
            -d project_name=postmodern-python \
            -d python_version=3.13 \
            -d user_email=you@example.com \
            -d user_name="Your Name" \
            . ../rendered-project/

      - name: Test rendered project
        working-directory: ${{ github.workspace }}/rendered-project
        run: |
          uv sync --all-extras --locked
          uv run poe ci:fmt
          uv run poe ci:lint
          uv run poe ci:deps
          uv run poe check
          uv run poe test
